/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class SBWallpaperEffectView, UIImage;

__attribute__((visibility("hidden")))
@interface _SBDockBackgroundView : UIView {
	UIImage* _maskImage;
	float _maskHeight;
	SBWallpaperEffectView* _maskedView;
	SBWallpaperEffectView* _unmaskedView;
}
-(void)setStyle:(int)style;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithMaskImage:(id)maskImage;
@end

