/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface _SBFakeBlurImage : NSObject {
	UIImage* _image;
	int _style;
}
@property(readonly, assign, nonatomic) int style;
@property(readonly, assign, nonatomic) UIImage* image;
-(void)dealloc;
-(id)initWithImage:(id)image style:(int)style;
@end

