/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIRemoteAlertHostInterface.h"
#import <UIKit/_UIRemoteViewController.h>

@class NSString;
@protocol _SBRemoteAlertHostViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface _SBRemoteAlertHostViewController : _UIRemoteViewController <SBUIRemoteAlertHostInterface> {
	id<_SBRemoteAlertHostViewControllerDelegate> _delegate;
	NSString* _serviceClassName;
}
@property(copy, nonatomic) NSString* serviceClassName;
@property(assign, nonatomic) id<_SBRemoteAlertHostViewControllerDelegate> delegate;
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)viewServiceDidTerminateWithError:(id)viewService;
-(void)dismiss;
-(id)description;
@end

