/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UIRemoteViewController.h>


__attribute__((visibility("hidden")))
@interface _SBWidgetPresentedViewController_Proxy : _UIRemoteViewController {
}
+(id)exportedInterface;
+(id)serviceViewControllerInterface;
@end

