/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSArray.h>


@interface NSArray (AlertItemsAdditions)
-(void)addUniqueObjectsOfClass:(Class)aClass toArray:(id)array;
-(id)objectOfClass:(Class)aClass;
@end

@interface NSArray (SpringBoard)
-(id)sbf_map:(id)map;
-(void)sbf_each:(id)each;
-(id)sbf_filter:(id)filter;
-(id)sbf_firstObjectPassingTest:(id)test;
@end

