/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSDictionary.h>


@interface NSDictionary (CTHelpers)
-(id)callingNamePresentationValue;
-(CFStringRef)settingType;
-(id)mmiProcedure;
-(id)ssServiceType;
-(id)serviceCenterAddress;
-(id)enabledString;
-(id)connectedLinePresentationValue;
-(id)connectedLineIDRestrictionValue;
-(id)callingLinePresentationValue;
-(id)callingLineIDRestrictionValue;
-(id)callBarringFacility;
-(id)callForwardingReason;
-(id)callClass;
@end

@interface NSDictionary (SBOptimizedCombination)
-(id)dictionaryByAddingEntriesFromDictionary:(id)dictionary;
@end

