/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSOperationQueue.h>


@interface NSOperationQueue (SBAdditions)
-(void)logStateOperationCountGreaterThan:(int)than;
@end

