/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>


@interface NSString (SpringBoardContextHosting)
-(BOOL)sbs_hasBeenOverridenAlready;
-(void)sbs_setHasBeenOverriddenAlready:(BOOL)already;
@end

@interface NSString (SBAdditions)
-(BOOL)sb_containsEmoji;
-(BOOL)sb_containsNonLatinLikeCharacters;
@end

