/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBActivationInfoViewController : UIViewController {
	NSString* _meid;
	NSString* _imei;
	NSString* _iccid;
	float _alertHeight;
}
-(id)_formattedIMEI;
-(id)_formattedICCID;
-(void)_simStatusChanged:(id)changed;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)_updateTextView;
-(id)textView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

