/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>


__attribute__((visibility("hidden")))
@interface SBAlertItemsSettings : _UISettings {
	BOOL _disableBBHandlers;
	int _testItemToken;
}
@property(assign, nonatomic) int testItemToken;
@property(assign, nonatomic) BOOL disableBBHandlers;
+(id)newTestItemForToken:(int)token;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

