/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBUISwitcherPageHostInterface.h"
#import <UIKit/_UIRemoteViewController.h>


__attribute__((visibility("hidden")))
@interface SBAppSwitcherPageServiceRemoteViewController : _UIRemoteViewController <_SBUISwitcherPageHostInterface> {
}
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

