/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBApplicationTerminationAssertionManager : NSObject {
	NSMutableDictionary* _assertionsByDisplayId;
}
+(id)sharedInstance;
-(void)_removeTerminationAssertion:(id)assertion;
-(void)_addTerminationAssertion:(id)assertion;
-(BOOL)_canAcquireTerminationAssertionForDisplayId:(id)displayId reason:(unsigned char)reason error:(char*)error;
-(id)acquireTerminationAssertionForDisplayId:(id)displayId withReason:(unsigned char)reason error:(char*)error;
-(id)terminationAssertionsForDisplayId:(id)displayId withReason:(unsigned char)reason;
-(id)terminationAssertionsForDisplayId:(id)displayId;
-(void)dealloc;
-(id)init;
@end

