/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, SBApplication;

__attribute__((visibility("hidden")))
@interface SBApplicationActivationAssertion : NSObject {
	SBApplication* _app;
	NSString* _name;
}
@property(copy, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) SBApplication* application;
-(void)dealloc;
-(id)initWithApplication:(id)application name:(id)name;
@end

