/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSHashTable, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface SBAppStatusBarManager : NSObject {
	NSHashTable* _disableAlphaChangeAssertions;
	NSMutableOrderedSet* _windowLevelOverrideReasons;
	NSMutableDictionary* _windowLevelOverrideMap;
	float _defaultWindowLevel;
}
+(id)sharedInstance;
-(void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)assertion;
-(void)_addDisableAppStatusBarAlphaChangesAssertion:(id)assertion;
-(void)_updateWindowLevel;
-(void)removeWindowLevelOverrideReason:(id)reason;
-(void)setWindowLevel:(float)level forOverrideReason:(id)overrideReason;
-(void)setDefaultWindowLevel:(float)level;
-(void)setStatusBarAlpha:(float)alpha;
-(void)hideStatusBar;
-(void)showStatusBar;
-(BOOL)isStatusBarHidden;
-(void)dealloc;
-(id)init;
@end

