/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBAppSwitcherServices;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherServiceManager : NSObject {
	SBAppSwitcherServices* _services;
}
+(id)sharedInstance;
-(id)registeredServicesSnapshot;
-(void)unregisterService:(id)service;
-(void)registerService:(id)service;
-(void)dealloc;
@end

