/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class _UIBackdropView;

__attribute__((visibility("hidden")))
@interface SBBackdropContainerView : UIView {
	_UIBackdropView* _backdropView;
}
@property(retain, nonatomic) _UIBackdropView* backdropView;
@property(readonly, assign, nonatomic) UIView* contentView;
-(void)layoutSubviews;
-(void)_reallyInsertSubview:(id)subview atIndex:(int)index;
-(void)insertSubview:(id)subview atIndex:(int)index;
-(void)addSubview:(id)subview;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

