/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "SBUIBannerView.h"

@class UIColor, SBBannerViewCallbackManager, SBUIBannerContext, UIImage, _UIBackdropView, UIImageView;

__attribute__((visibility("hidden")))
@interface SBBannerContextView : UIView <SBUIBannerView> {
	UIEdgeInsets _clippingInsets;
	UIView* _clippingView;
	SBUIBannerContext* _context;
	UIView<SBUIBannerView>* _contentView;
	SBBannerViewCallbackManager* _callbacks;
	SBBannerViewCallbackManager* _wrapperCallbacks;
	_UIBackdropView* _backdropView;
	UIImageView* _backgroundImageView;
	struct {
		unsigned delegateOverrideRequester : 1;
		unsigned delegateShouldEnableContextHostingForRequester : 1;
	} _contentViewFlags;
}
@property(copy, nonatomic) UIColor* grabberColor;
@property(readonly, assign, nonatomic) UIColor* defaultGrabberColor;
@property(retain, nonatomic) UIImage* backgroundImage;
@property(readonly, assign, nonatomic) _UIBackdropView* backdrop;
@property(assign, nonatomic) UIEdgeInsets clippingInsets;
+(id)defaultGrabberColor;
-(id)bannerContext;
-(void)layoutSubviews;
-(CGRect)_frameInClippingViewForFrame:(CGRect)frame;
-(void)noteDidDismissWithReason:(int)note;
-(void)noteWillDismissWithReason:(int)note;
-(void)noteDidAppear;
-(void)noteWillAppear;
-(void)setBannerContext:(id)context withReplaceReason:(int)replaceReason;
-(CGRect)_contentFrame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

