/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SBBBInfoOperation : NSObject {
	id _operand;
}
@property(readonly, assign, nonatomic) id operand;
+(id)operationWithOperand:(id)operand;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithOperand:(id)operand;
@end

