/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>
#import "_UIDynamicReferenceSystem.h"


__attribute__((visibility("hidden")))
@interface SBBouncingSystem : NSObject <_UIDynamicReferenceSystem> {
	CGRect _bounds;
}
@property(assign) CGRect bounds;
@end

