/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>


__attribute__((visibility("hidden")))
@interface SBCarDisplaySettings : _UISettings {
	int _lockOutMode;
	int _lockOutAnimationType;
}
@property(assign) int lockOutAnimationType;
@property(assign) int lockOutMode;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

