/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBUIControlCenterButton.h>

@class NSString, NSNumber;

__attribute__((visibility("hidden")))
@interface SBControlCenterButton : SBUIControlCenterButton {
	NSString* _identifier;
	NSNumber* _sortKey;
}
@property(copy, nonatomic) NSNumber* sortKey;
@property(copy, nonatomic) NSString* identifier;
-(void)dealloc;
@end

