/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIControlCenterControlObserver.h"
#import <UIKit/UIView.h>
#import "SBControlCenterObserver.h"
#import "SpringBoard-Structs.h"

@class SBChevronView, NSMutableArray, SBUIControlCenterLabel, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBControlCenterGrabberView : UIView <SBUIControlCenterControlObserver, SBControlCenterObserver> {
	SBChevronView* _chevronView;
	SBUIControlCenterLabel* _statusLabel;
	SBUIControlCenterLabel* _statusLabel2;
	BOOL _statusBusy;
	NSMutableDictionary* _statusByReason;
	NSMutableArray* _statusReasonQueue;
}
+(float)defaultHeightForOrientation:(int)orientation;
-(void)controlConfigurationDidChangeForState:(int)controlConfiguration;
-(void)controlAppearanceDidChangeForState:(int)controlAppearance;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)layoutSubviews;
-(CGRect)_grabberRect;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)updateStatusText:(id)text reason:(id)reason;
-(void)_animateNextStatus;
-(void)_didPresentStatus;
-(void)_dequeueStatus;
-(id)_popNextStatus;
-(BOOL)_hasPendingStatus;
-(id)chevronView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

