/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface SBControlCenterSectionView : UIView {
	float _edgePadding;
}
@property(assign, nonatomic) float edgePadding;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

