/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "SBControlCenterObserver.h"
#import "SpringBoard-Structs.h"

@class NSString;
@protocol SBControlCenterSectionViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBControlCenterSectionViewController : UIViewController <SBControlCenterObserver> {
	id<SBControlCenterSectionViewControllerDelegate> _delegate;
}
@property(readonly, assign, nonatomic) NSString* sectionIdentifier;
@property(assign, nonatomic) id<SBControlCenterSectionViewControllerDelegate> delegate;
+(Class)viewClass;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)noteSettingsDidUpdate:(id)noteSettings;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(BOOL)enabledForOrientation:(int)orientation;
-(id)view;
-(void)loadView;
@end

