/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDateLabelDelegate.h"
#import <UIKit/UIView.h>
#import "SBUIBannerView.h"
#import "SpringBoard-Structs.h"

@class UIColor, UILabel, SBDefaultBannerTextView, SBUIBannerContext, UIImageView;
@protocol SBBulletinDateLabel, SBDefaultBannerViewSource;

__attribute__((visibility("hidden")))
@interface SBDefaultBannerView : UIView <SBDateLabelDelegate, SBUIBannerView> {
	SBUIBannerContext* _context;
	id<SBDefaultBannerViewSource> _viewSource;
	UIImageView* _iconImageView;
	UILabel<SBBulletinDateLabel>* _relevanceDateLabel;
	SBDefaultBannerTextView* _textView;
	UIImageView* _attachmentImageView;
	CGSize _grabberSize;
	UIView* _grabberView;
}
@property(copy, nonatomic) UIColor* grabberColor;
+(id)defaultGrabberColor;
-(void)dateLabelDidChange:(id)dateLabel;
-(void)layoutSubviews;
-(id)bannerContext;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithContext:(id)context;
@end

