/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDistanceFieldView : UIView {
}
@property(assign) float lineWidth;
@property(assign) float sharpness;
@property(assign) float offset;
@property(assign) CGColorRef foregroundColor;
@property(assign) BOOL invertsShape;
@property(copy, nonatomic) NSString* renderMode;
+(Class)layerClass;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

