/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWallpaperObserver.h"
#import <UIKit/UIView.h>

@class SBHighlightView, SBDockIconListView, UIImageView, _SBDockBackgroundView;

__attribute__((visibility("hidden")))
@interface SBDockView : UIView <SBWallpaperObserver> {
	SBDockIconListView* _iconListView;
	SBHighlightView* _highlightView;
	_SBDockBackgroundView* _backgroundView;
	UIImageView* _backgroundImageView;
}
+(float)defaultHeight;
-(void)wallpaperDidChangeForVariant:(int)wallpaper;
-(id)_newBackgroundImage;
-(void)setVerticalBackgroundStretch:(float)stretch;
-(void)setBackgroundAlpha:(float)alpha;
-(float)heightForOrientation:(int)orientation;
-(void)layoutSubviews;
-(id)dockListView;
-(void)dealloc;
-(id)initWithDockListView:(id)dockListView forSnapshot:(BOOL)snapshot;
@end

