/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>


__attribute__((visibility("hidden")))
@interface SBFolderSettings : _UISettings {
	BOOL _allowNestedFolders;
	BOOL _pinchToClose;
	BOOL _blurFolderBackground;
	BOOL _oneColumnAtATime;
}
@property(assign, nonatomic) BOOL oneColumnAtATime;
@property(assign, nonatomic) BOOL blurFolderBackground;
@property(assign, nonatomic) BOOL pinchToClose;
@property(assign, nonatomic) BOOL allowNestedFolders;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

