/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWallpaperObserver.h"
#import <UIKit/UIView.h>
#import "_UISettingsKeyObserver.h"

@class UIImageView, SBWallpaperEffectView, SBFolderSettings;

__attribute__((visibility("hidden")))
@interface SBFolderBackgroundView : UIView <_UISettingsKeyObserver, SBWallpaperObserver> {
	SBWallpaperEffectView* _backdropView;
	UIImageView* _backgroundImageView;
	SBFolderSettings* _folderSettings;
}
+(float)cornerRadiusToInsetContent;
+(CGSize)folderBackgroundSize;
-(void)wallpaperDidChangeForVariant:(int)wallpaper;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_configureBackground;
-(void)adjustCornerRadiusForMagnificationFraction:(float)magnificationFraction;
-(void)didAnimate;
-(void)willAnimate;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

