/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface SBGradientView : UIView {
	NSArray* _colors;
}
@property(assign) CGPoint endPoint;
@property(assign) CGPoint startPoint;
@property(copy, nonatomic) NSArray* locations;
@property(copy, nonatomic) NSArray* colors;
+(Class)layerClass;
-(id)color;
@end

