/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCountedMapValue.h"
#import <UIKit/UIImage.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBIconAccessoryImage : UIImage <SBCountedMapValue> {
	NSString* _countedMapKey;
}
@property(copy, nonatomic) NSString* countedMapKey;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

