/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>

@class SBFAnimationSettings;

__attribute__((visibility("hidden")))
@interface SBIconAnimationSettings : _UISettings {
	SBFAnimationSettings* _centralAnimationSettings;
}
@property(retain) SBFAnimationSettings* centralAnimationSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

