/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIScrollView.h>
#import "SpringBoard-Structs.h"

@protocol SBIconScrollViewDelegate;

__attribute__((visibility("hidden")))
@interface SBIconScrollView : UIScrollView {
}
@property(assign, nonatomic) id<SBIconScrollViewDelegate> delegate;
-(void)setContentOffset:(CGPoint)offset;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(BOOL)cancelTouchTracking;
@end

