/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>


__attribute__((visibility("hidden")))
@interface SBImageAlertView : UIAlertView {
	BOOL _showingImage;
}
-(BOOL)isShowingImage;
-(void)setImage:(id)image;
-(void)layout;
@end

