/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import <UIKit/UIScrollView.h>

@class SBLockScreenNotificationCell;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationScrollView : UIScrollView <UIGestureRecognizerDelegate> {
	SBLockScreenNotificationCell* _associatedCell;
}
@property(assign, nonatomic) SBLockScreenNotificationCell* associatedCell;
+(float)scrollThresholdForPasscodeScroll;
@end

