/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class UIAlertView;

__attribute__((visibility("hidden")))
@interface SBLockScreenModalAlertView : UIView {
	UIAlertView* _alertView;
	UIView* _realModalAlertView;
}
-(void)layoutSubviews;
-(void)removeAlertView;
-(void)showAlertView:(id)view;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

