/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationBannerItemFactory : NSObject {
}
+(id)sharedInstance;
-(id)bannerItemWithAwayListItem:(id)awayListItem unlockActionHandler:(id)handler delegate:(id)delegate;
-(BOOL)supportsAwayListItem:(id)item;
@end

