/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, SBAwayViewPluginController, SBLockOverlayContext;

__attribute__((visibility("hidden")))
@interface SBLockScreenPlugin : NSObject {
	SBAwayViewPluginController* _controller;
	SBLockOverlayContext* _overlay;
	NSString* _bundleName;
}
@property(copy) NSString* bundleName;
@property(retain) SBLockOverlayContext* overlay;
@property(retain) SBAwayViewPluginController* controller;
-(void)dealloc;
@end

