/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBAwayViewPluginController, SBLockOverlayContext, SBLockScreenViewController;

__attribute__((visibility("hidden")))
@interface SBLockScreenPluginTransitionContext : NSObject {
	SBLockScreenViewController* _lockScreenViewController;
	SBAwayViewPluginController* _fromController;
	SBLockOverlayContext* _fromOverlay;
	SBAwayViewPluginController* _toController;
	SBLockOverlayContext* _toOverlay;
}
@property(assign) SBLockOverlayContext* toOverlay;
@property(assign) SBAwayViewPluginController* toController;
@property(assign) SBLockOverlayContext* fromOverlay;
@property(assign) SBAwayViewPluginController* fromController;
@property(assign) SBLockScreenViewController* lockScreenViewController;
@end

