/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class SBLockScreenBatteryChargingView, NSTimer;
@protocol SBLockScreenBatteryChargingViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenBatteryChargingViewController : UIViewController {
	SBLockScreenBatteryChargingView* _chargingView;
	NSTimer* _visibilityTimer;
	BOOL _displayDetailedCharge;
	int _chargePercentage;
	id<SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBLockScreenBatteryChargingViewControllerDelegate> delegate;
-(void)_batteryStatusChanged:(id)changed;
-(void)_visibilityTimerFired:(id)fired;
-(void)showChargeLevelWithBatteryVisible:(BOOL)batteryVisible;
-(id)chargingView;
-(BOOL)batteryVisible;
-(void)_clearVisibilityTimer;
-(void)prepareForDismissal;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

