/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBUILockScreenDisableAssertion.h>

@class SBPasscodeLockDisableAssertion, NSString;

__attribute__((visibility("hidden")))
@interface SBLockScreenDisableAssertion : SBUILockScreenDisableAssertion {
	NSString* _identifier;
	SBPasscodeLockDisableAssertion* _disableLockAssertion;
}
+(void)initialize;
-(void)dealloc;
-(id)description;
-(id)initWithIdentifier:(id)identifier;
@end

