/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@protocol SBLockOverlayViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBLockOverlayViewController : UIViewController {
	id<SBLockOverlayViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBLockOverlayViewControllerDelegate> delegate;
-(id)overlayView;
@end

