/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SBLockScreenPluginLoader : NSObject {
}
-(Class)_principleClassFromBundleWithName:(id)name;
-(BOOL)_verifyPrincipleClass:(Class)aClass fromBundleWithName:(id)name;
-(id)_pluginControllerFromPrincipalClass:(Class)principalClass;
-(id)pluginControllerForName:(id)name activationContext:(id)context;
@end

