/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBounceBehaviorDelegate.h"
#import "UIDynamicAnimatorDelegate.h"
#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"

@class SBBounceBehavior, SBBounceSettings, UIDynamicAnimator, SBBouncingSystem, _SBNotificationCenterBouncingItem;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterBounceAnimator : NSObject <UIDynamicAnimatorDelegate, SBBounceBehaviorDelegate> {
	UIDynamicAnimator* _animator;
	SBBouncingSystem* _system;
	SBBounceBehavior* _behavior;
	_SBNotificationCenterBouncingItem* _item;
	id _completion;
	SBBounceSettings* _settings;
	CGRect _targetFrame;
	BOOL _didBounce;
}
@property(copy, nonatomic, getter=_completion, setter=_setCompletion:) id completion;
@property(retain, nonatomic, getter=_behavior, setter=_setBehavior:) SBBounceBehavior* behavior;
@property(readonly, assign, nonatomic, getter=_animator) UIDynamicAnimator* animator;
-(void)bounceBehaviorDidBounce:(id)bounceBehavior;
-(void)dynamicAnimatorDidPause:(id)dynamicAnimator;
-(void)_updateSettings;
-(void)beginBounceWithInitialFrame:(CGRect)initialFrame targetFrame:(CGRect)frame velocity:(CGPoint)velocity stepper:(id)stepper completion:(id)completion;
-(void)dealloc;
-(id)initWithReferenceBounds:(CGRect)referenceBounds settings:(id)settings;
@end

