/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIControl.h>


__attribute__((visibility("hidden")))
@interface SBNotificationsClearButton : UIControl {
}
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(id)initWithImage:(id)image;
@end

