/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>

@class SBBounceSettings;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterSettings : _UISettings {
	SBBounceSettings* _bounceSettings;
	float _modeButtonTintLevel;
	float _modeButtonTintAlpha;
	float _modeLabelTintLevel;
	float _modeLabelTintAlpha;
	double _grabberAnimationDuration;
}
@property(assign, nonatomic) float modeLabelTintAlpha;
@property(assign, nonatomic) float modeLabelTintLevel;
@property(assign, nonatomic) float modeButtonTintAlpha;
@property(assign, nonatomic) float modeButtonTintLevel;
@property(assign) double grabberAnimationDuration;
@property(retain, nonatomic) SBBounceSettings* bounceSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

