/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray, SBOperation, NSHashTable;

__attribute__((visibility("hidden")))
@interface SBOperationQueue : NSObject {
	NSString* _name;
	NSMutableArray* _operationQueue;
	NSHashTable* _operationLocks;
	SBOperation* _executingOperation;
}
@property(retain, nonatomic) SBOperation* executingOperation;
-(void)_processNextOperationIfNecessary;
-(void)_executeOrPendOperations:(id)operations;
-(void)_removeOperationQueueLock:(id)lock;
-(void)_addOperationQueueLock:(id)lock;
-(id)description;
-(void)executeOrAppendOperation:(id)operation;
-(id)acquireLockForReason:(id)reason;
-(BOOL)isLocked;
-(void)dealloc;
-(id)initWithName:(id)name;
@end

