/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBOperation : NSObject {
	id _block;
	NSString* _name;
	BOOL _hasRun;
}
@property(readonly, assign, nonatomic) NSString* name;
+(id)operationWithBlock:(id)block name:(id)name;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)description;
-(void)execute;
-(void)dealloc;
-(id)initWithBlock:(id)block name:(id)name;
@end

