/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "SBTestRecipe.h"

@class SBPasscodeEntryAlertViewController;

__attribute__((visibility("hidden")))
@interface SBPasscodeAlertRecipe : NSObject <SBTestRecipe> {
	SBPasscodeEntryAlertViewController* _alert;
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)dealloc;
@end

