/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBPasscodeLockAssertionTracker;

__attribute__((visibility("hidden")))
@interface SBPasscodeLockAssertionManager : NSObject {
	SBPasscodeLockAssertionTracker* _preventLockTracker;
	SBPasscodeLockAssertionTracker* _lockScreenCameraTracker;
	SBPasscodeLockAssertionTracker* _siriTracker;
	SBPasscodeLockAssertionTracker* _transientTracker;
}
-(id)description;
-(BOOL)hasActiveAssertions;
-(void)removeAssertion:(id)assertion;
-(void)addAssertion:(id)assertion;
-(void)dealloc;
-(id)init;
@end

