/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBPowerDownViewInterface.h"
#import "UIGestureRecognizerDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBAlertView.h"

@class SBFGlintyStringView, SBFakeStatusBarView, NSTimer, UIPanGestureRecognizer, UILongPressGestureRecognizer, UILabel, SBShapeView, _UIBackdropView;
@protocol SBPowerDownViewDelegate;

__attribute__((visibility("hidden")))
@interface SBPowerDownView : SBAlertView <SBPowerDownViewInterface, UIGestureRecognizerDelegate> {
	NSTimer* _autoDismissTimer;
	id<SBPowerDownViewDelegate> _delegate;
	SBFakeStatusBarView* _fakeStatusBarView;
	SBShapeView* _darkeningOutsideBarsUnderlay;
	SBShapeView* _darkeningInsideBarsUnderlay;
	UIView* _topContainer;
	UIView* _topBar;
	SBFGlintyStringView* _topBarLabel;
	UIView* _topBarLabelBackgroundView;
	_UIBackdropView* _topBarBackground;
	UIView* _bottomContainer;
	UIView* _bottomBar;
	UILabel* _bottomBarLabel;
	_UIBackdropView* _bottomBarBackground;
	BOOL _addedFakeStatusBar;
	BOOL _hiddenLockScreenForeground;
	UIPanGestureRecognizer* _slideGestureRecognizer;
	UILongPressGestureRecognizer* _touchGestureRecognizer;
	CGPoint _slideGestureInitialPoint;
}
@property(assign, nonatomic) id<SBPowerDownViewDelegate> delegate;
-(id)_insideBarsPath;
-(id)_outsideBarsPath;
-(void)_animatePowerDown;
-(void)_slideCompleted:(BOOL)completed;
-(void)_notifyDelegateCancelled;
-(void)_notifyDelegatePowerDown;
-(void)_resetAutoDismissTimer;
-(void)_cancelAutoDismissTimer;
-(id)_newDarkeningShapeView:(CGRect)view;
-(void)_removeFakeStatusBarIfNecessary;
-(void)_addFakeStatusBarIfNecessary;
-(id)_lockScreenView;
-(float)_bottomBarOffset;
-(float)_topBarOffset;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)_touchGestureRecognizer:(id)recognizer;
-(void)_slideGestureRecognizer:(id)recognizer;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isSupportedInterfaceOrientation:(int)orientation;
-(void)animateOut;
-(void)animateIn;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

