/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "UIAlertViewDelegate.h"


__attribute__((visibility("hidden")))
@interface SBPPTAlertViewDelegate : NSObject <UIAlertViewDelegate> {
}
-(void)didPresentAlertView:(id)view;
@end

