/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/_UISettings.h>

@class SBCarDisplaySettings, SBLockScreenSettings, SBLegibilitySettings, SBFWallpaperSettings, SBAlertItemsSettings, SBFAnimationFactorySettings, SBNotificationCenterSettings, SBFolderSettings, SBLockScreenTestPluginSettings, SBAppParallaxSettings, SBRootAnimationSettings, SBControlCenterSettings, SBAppSliderSettings, SBFadeAnimationSettings, SBIconColorSettings, NSString;

__attribute__((visibility("hidden")))
@interface SBRootSettings : _UISettings {
	BOOL _preventLockover;
	SBAppParallaxSettings* _parallaxSettings;
	SBFolderSettings* _folderSettings;
	SBRootAnimationSettings* _rootAnimationSettings;
	SBControlCenterSettings* _controlCenterSettings;
	SBAppSliderSettings* _appSliderSettings;
	SBLockScreenSettings* _lockScreenSettings;
	SBCarDisplaySettings* _carDisplaySettings;
	SBLockScreenTestPluginSettings* _lockScreenTestPluginSettings;
	SBIconColorSettings* _iconColorSettings;
	SBFadeAnimationSettings* _fadeAnimationSettings;
	SBAlertItemsSettings* _alertItemsSettings;
	SBNotificationCenterSettings* _notificationCenterSettings;
	SBLegibilitySettings* _legibilitySettings;
	SBFWallpaperSettings* _wallpaperSettings;
	SBFAnimationFactorySettings* _animationSettings;
	NSString* _testRecipeClassName;
}
@property(assign) BOOL preventLockover;
@property(retain) NSString* testRecipeClassName;
@property(retain) SBFAnimationFactorySettings* animationSettings;
@property(retain) SBFWallpaperSettings* wallpaperSettings;
@property(retain) SBLegibilitySettings* legibilitySettings;
@property(retain) SBNotificationCenterSettings* notificationCenterSettings;
@property(retain) SBAlertItemsSettings* alertItemsSettings;
@property(retain) SBFadeAnimationSettings* fadeAnimationSettings;
@property(retain) SBIconColorSettings* iconColorSettings;
@property(retain) SBLockScreenTestPluginSettings* lockScreenTestPluginSettings;
@property(retain) SBCarDisplaySettings* carDisplaySettings;
@property(retain) SBLockScreenSettings* lockScreenSettings;
@property(retain) SBAppSliderSettings* appSliderSettings;
@property(retain) SBControlCenterSettings* controlCenterSettings;
@property(retain) SBRootAnimationSettings* rootAnimationSettings;
@property(retain) SBFolderSettings* folderSettings;
@property(retain) SBAppParallaxSettings* parallaxSettings;
+(id)settingsControllerModule;
-(BOOL)_hasPreviousSettings;
-(void)setDefaultValues;
@end

