/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class _UIBackdropView, SBWallpaperEffectView;

__attribute__((visibility("hidden")))
@interface SBSearchResultsBackdropView : UIView {
	_UIBackdropView* _backdropView;
	SBWallpaperEffectView* _effectView;
	UIView* _tintView;
}
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

