/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Search/SPSearchAgent.h>
#import "SPDaemonQueryDelegate.h"

@class NSObject, CPLRUDictionary, NSDate, NSOperationQueue, NSTimer, NSOperation;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface SBSearchModel : SPSearchAgent <SPDaemonQueryDelegate> {
	NSTimer* _clearSearchTimer;
	NSDate* _clearSearchDate;
	CPLRUDictionary* _cachedResultImages;
	NSObject<OS_dispatch_semaphore>* _cacheResultLock;
	NSOperationQueue* _prefetchOperationQueue;
	NSOperationQueue* _loadOperationQueue;
	NSOperation* _waitOperation;
	void* _addressBook;
}
+(id)sharedInstance;
-(id)currentToken;
-(id)operationFetchingImageForResult:(id)result inSection:(id)section withCompletionBlock:(id)completionBlock;
-(BOOL)prefetchImageForResult:(id)result inSection:(id)section;
-(void)cancelPrefetchingAndStartNewBatch;
-(id)cachedImageForResult:(id)result inSection:(id)section;
-(void)fetchImageForResult:(id)result inSection:(id)section withCompletionBlock:(id)completionBlock;
-(void)_cacheImage:(id)image forKey:(id)key withCompletionBlock:(id)completionBlock;
-(id)_imageForResult:(id)result inSection:(id)section withCompletionBlock:(id)completionBlock;
-(id)_uniqueKeyForResult:(id)result withSearchDomain:(unsigned)searchDomain;
-(id)_customImageForPath:(id)path;
-(void)handleOptionsForNewSections:(id)newSections;
-(void)invalidate;
-(id)launchingURLForResult:(id)result withDisplayIdentifier:(id)displayIdentifier andSection:(id)section;
-(void)_updateClearSearchTimerFireDate;
-(void)startClearSearchTimer;
-(void)_clearSearchTimerFired;
-(void)resetClearSearchTimer;
-(void)dealloc;
-(id)init;
@end

