/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface SBShapeView : UIView {
}
+(Class)layerClass;
-(id)_shapeLayer;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setFillRule:(int)rule;
-(void)setFillColor:(id)color;
-(void)setPath:(id)path;
@end

