/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@protocol SBSizeObservingViewDelegate;

__attribute__((visibility("hidden")))
@interface SBSizeObservingView : UIView {
	BOOL _delegateInterestedInSizeChanges;
	id<SBSizeObservingViewDelegate> _delegate;
}
@property(assign, nonatomic) id<SBSizeObservingViewDelegate> delegate;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
@end

