/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface SBStarkLockOutAnimation : NSObject {
	int _type;
	UIView* _snapshotView;
	int _statusBarStyle;
	BOOL _statusBarHidden;
}
@property(assign, nonatomic) BOOL statusBarHidden;
@property(assign, nonatomic) int statusBarStyle;
@property(retain, nonatomic) UIView* snapshotView;
@property(assign, nonatomic) int type;
-(id)description;
-(void)dealloc;
@end

