/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBStarkBackgroundProvider : NSObject {
	NSString* _serviceName;
	NSString* _viewControllerClassName;
	unsigned _priority;
}
@property(readonly, assign, nonatomic) unsigned priority;
@property(readonly, assign, nonatomic) NSString* viewControllerClassName;
@property(readonly, assign, nonatomic) NSString* serviceName;
-(id)description;
-(void)dealloc;
-(id)initWithServiceName:(id)serviceName viewControllerClassName:(id)name priority:(unsigned)priority;
-(id)initWithServiceName:(id)serviceName options:(id)options;
@end

