/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBStarkFakeIconOperationController : NSObject {
	NSMutableDictionary* _launchOperationForDisplayIDMap;
}
-(void)addLaunchOperation:(id)operation withDisplayID:(id)displayID;
-(BOOL)performOperationForFakeIconWithDisplayID:(id)displayID;
-(void)dealloc;
-(id)init;
@end

