/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBUIBannerItem.h>

@class NSMutableSet, NSString, NSArray, NSHashTable, UIImage;

__attribute__((visibility("hidden")))
@interface SBStarkBannerItem : SBUIBannerItem {
	NSHashTable* _observers;
	NSMutableSet* _displayReasons;
}
@property(readonly, assign, nonatomic) NSArray* subActionLabels;
@property(readonly, assign, nonatomic) int actionType;
@property(readonly, assign, nonatomic) UIImage* categoryImage;
@property(readonly, assign, nonatomic) NSString* subTitle;
@property(readonly, assign, nonatomic) NSString* title;
-(BOOL)isStarkBannerItem;
-(BOOL)matchesContext:(id)context;
-(void)reloadDisplayProperties;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)dealloc;
-(id)init;
@end

