/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "_UIBasicAnimationFactory.h"


__attribute__((visibility("hidden")))
@interface SBStarkSlideAnimationFactory : NSObject <_UIBasicAnimationFactory> {
	double _startTime;
}
@property(assign, nonatomic) double startTime;
-(id)_timingFunctionForAnimation;
-(id)_basicAnimationForView:(id)view withKeyPath:(id)keyPath;
@end

