/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UICollectionViewLayoutAttributes.h>


__attribute__((visibility("hidden")))
@interface SBStarkLauncherLayoutAttributes : UICollectionViewLayoutAttributes {
	BOOL _lastIcon;
}
@property(assign, nonatomic, getter=isLastIcon) BOOL lastIcon;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(id)copyWithZone:(NSZone*)zone;
@end

