/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "SBStarkBannerItemObserver.h"
#import "SBUIBannerView.h"

@class UIColor, UILabel, SBUIBannerContext, SBStarkBannerItem, UIImageView;

__attribute__((visibility("hidden")))
@interface SBStarkBannerView : UIView <SBStarkBannerItemObserver, SBUIBannerView> {
	SBUIBannerContext* _context;
	SBStarkBannerItem* _bannerItem;
	UIImageView* _categoryImageView;
	UILabel* _titleLabel;
	float _titleAscender;
	UILabel* _subTitleLabel;
	float _subTitleAscender;
	UIImageView* _actionImageView;
	UIEdgeInsets _contentInsets;
}
@property(copy, nonatomic) UIColor* grabberColor;
+(UIEdgeInsets)_contentInsetsForActionType:(int)actionType;
+(id)_imageForActionType:(int)actionType;
-(void)starkBannerItemDidReloadDisplayProperties:(id)starkBannerItem;
-(id)bannerContext;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithContext:(id)context;
@end

