/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface SBTodayTableHeaderView : UIView {
	UILabel* _dateLabel;
}
+(id)defaultFont;
+(id)defaultTextColor;
+(id)defaultBackgroundColor;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGRect)dateLabelFrame;
-(void)updateContent;
-(id)dateHeaderAttributedString;
-(id)dateHeader;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

