/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <SpringBoardFoundation/_SBFVibrantTableViewCell.h>

@class NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface SBTodayBulletinCell : _SBFVibrantTableViewCell {
	UILabel* _label;
	UIImageView* _iconImageView;
}
@property(copy, nonatomic) NSString* labelText;
@property(assign, nonatomic) CGRect textRect;
+(id)defaultTextAttributes;
+(id)defaultFontColor;
+(id)defaultFont;
-(void)layoutSubviews;
-(void)setIcon:(id)icon;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

