/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIColor;

@protocol SBUIBannerView <NSObject>
@optional
@property(copy, nonatomic) UIColor* grabberColor;
@required
-(id)bannerContext;
@optional
+(id)defaultGrabberColor;
@end

