/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class SBBBWidgetBulletinInfo;

__attribute__((visibility("hidden")))
@interface SBWidgetBulletinCell : UITableViewCell {
	SBBBWidgetBulletinInfo* _representedWidgetBulletinInfo;
}
@property(retain, nonatomic) SBBBWidgetBulletinInfo* representedWidgetBulletinInfo;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

