/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "SBWindowContextManagerObserver.h"

@class NSMutableSet, UIScreen, NSDictionary, SBWindowContextHostWrapperView, SBWindowContextManager;

__attribute__((visibility("hidden")))
@interface SBWindowContextHostInfo : NSObject <SBWindowContextManagerObserver> {
	SBWindowContextManager* _contextManager;
	UIScreen* _screen;
	SBWindowContextHostWrapperView* _wrapperView;
	NSMutableSet* _hiddenContexts;
	NSDictionary* _realContextHostViewChangedProperties;
	NSDictionary* _realContextHostViewOriginalProperties;
}
@property(retain, nonatomic) NSDictionary* realContextHostViewOriginalProperties;
@property(retain, nonatomic) NSDictionary* realContextHostViewChangedProperties;
@property(readonly, assign, nonatomic) NSMutableSet* hiddenContexts;
@property(readonly, assign, nonatomic) SBWindowContextHostWrapperView* wrapperView;
-(void)windowContextManager:(id)manager didRepositionContext:(id)context from:(unsigned)from to:(unsigned)to forScreen:(id)screen;
-(void)dealloc;
-(id)initWithContextManager:(id)contextManager hostManager:(id)manager screen:(id)screen jailBehavior:(int)behavior;
@end

