/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SBWindowHideState : NSObject {
	BOOL _hidden;
	float _desiredAlpha;
}
@property(assign) float desiredAlpha;
@property(assign, getter=isHidden) BOOL hidden;
-(id)description;
@end

