/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIScreen;

__attribute__((visibility("hidden")))
@interface SBWindowContext : NSObject {
	unsigned _identifier;
	float _level;
	UIScreen* _screen;
	BOOL _orderOutPending;
}
@property(assign, nonatomic, getter=isOrderOutPending) BOOL orderOutPending;
@property(readonly, assign, nonatomic) UIScreen* screen;
@property(readonly, assign, nonatomic) float level;
@property(readonly, assign, nonatomic) unsigned identifier;
+(id)contextWithIdentifier:(unsigned)identifier level:(float)level screen:(id)screen;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithIdentifier:(unsigned)identifier level:(float)level screen:(id)screen;
@end

