/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface SBWorkItem : NSObject {
	id _workBlock;
	NSDate* _creationDate;
}
@property(readonly, assign, nonatomic) NSDate* creationDate;
@property(readonly, assign, nonatomic) id work;
-(void)dealloc;
-(id)initWithWork:(id)work;
@end

