/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImage.h>


@interface UIImage (SBGraphics)
@property(readonly, assign, nonatomic) CGSize pixelSize;
+(id)sbg_imageFromContextWithSize:(CGSize)size scale:(float)scale type:(int)type pool:(id)pool drawing:(id)drawing encapsulation:(id)encapsulation;
+(id)sbg_imageFromContextWithSize:(CGSize)size scale:(float)scale type:(int)type pool:(id)pool drawing:(id)drawing;
+(unsigned long)sbg_bytesNeededForSize:(CGSize)size scale:(float)scale withContextType:(int)contextType;
-(CGImageRef)_newThumbnailWithJPEG:(id)jpeg forMaxPixelDimension:(float)maxPixelDimension;
-(CGImageRef)_newThumbnailWithImageSource:(CGImageSourceRef)imageSource forMaxPixelDimension:(float)maxPixelDimension;
-(id)_thumbnailFitToSize:(CGSize)size;
-(CGImageSourceRef)_newSource;
-(id)sbg_squareImage;
-(id)sbg_resizeImageToSize:(CGSize)size;
-(id)sbg_resizeImageToSize:(CGSize)size preservingAspectRatio:(BOOL)ratio;
-(id)sbg_thumbnailFitToSize:(CGSize)size;
-(BOOL)isAnimated;
-(id)sbg_memoryMappedImageWithPool:(id)pool;
@end

@interface UIImage (SBIconScales)
+(float)scaleForApplicationIconFormat:(int)applicationIconFormat;
@end

