/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UILabel.h>


@interface UILabel (SpringBoard)
-(float)sb_yPositionForLabelWithContainerBounds:(CGRect)containerBounds lineHeight:(float)height baselineOffset:(float)offset font:(id)font;
@end

@interface UILabel (SBStringDrawing)
-(void)drawWithMetrics:(id)metrics inContext:(CGContextRef)context;
-(id)stringMetricsForFirstLineWidth:(float)firstLineWidth;
@end

